[package]
name = "vault-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
rusqlite.workspace = true
blake3.workspace = true
rayon.workspace = true
walkdir.workspace = true
notify-debouncer-mini.workspace = true
regex.workspace = true
